spring.application.name=smfin
spring.datasource.url=jdbc:sqlite:smfin-sinan.db?foreign_keys=true
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql